### ISSUE TITLE
 elastool_aims does not work!

### ISSUE THREAD

**Issue by shahramyalameha** [yaoyi92/elastool_aims#1]
Hi
I used this code and tested the Si example. But the program encounters various errors. Has this program been tested?

thanks

**Comment by yaoyi92** [comment]
Dear Shahra,

It works for me. Can you describe the errors you have? I might be able to help.

**Comment by shahramyalameha** [comment]
Dear yaoyi,
Thank you for your reply. 
Please let me explain in more detail: I am using version` 231212` of Fhi-aims. Input files for Si are as follows:
### aims_opt_w_cell.json:
```
{

  "xc": "pbesol",
  "species_dir": "/home/shahram/Sotf/fhi-aims.231212/fhi-aims.231212/species_defaults/defaults_2020/intermediate",
  "sc_accuracy_rho": 1e-06,
  "sc_accuracy_forces": 0.0001,
  "relativistic": "atomic_zora scalar",
  "walltime": 40000.0,
  "sc_iter_limit": 200,
  "relax_geometry": "trm 1.e-2",
  "relax_unit_cell": "full"
}
```
### aims_opt_wo_cell.json:

```
{
  "xc": "pbesol",
  "species_dir": "/home/shahram/Sotf/fhi-aims.231212/fhi-aims.231212/species_defaults/defaults_2020/intermediate",
  "sc_accuracy_rho": 1e-06,
  "sc_accuracy_forces": 0.0001,
  "relativistic": "atomic_zora scalar",
  "walltime": 40000.0,
  "sc_iter_limit": 200,
  "relax_unit_cell": "none",
  "compute_analytical_stress": ".true."
}
```

elastool.in:

```
###############################################################################
### The input file to control the calculation details of elastic constants  ###
###############################################################################

# run mode: 0 for generating key default input files, 1 for automatic run, 2 for pre-processing, 3 for post-processing
# if 2, plz ensure the structure opt. is performed at fixed pressure or volume
# i.e. CONTCAR and OUTCAR files both exist in ./OPT directory.
#Additionally, you can visualize elastic parameters directly using Elate by running "elastool -elate" after strain-stress calculations
run_mode = 1

# Define the dimensional of the system: 1D/2D/3D. 
dimensional = 3D

# the crystal structure file in vasp POSCAR (.vasp) or cif (.cif) format
structure_file = geometry.in

# if use conventional cell, no for primitive cell, yes for conventional cell
if_conventional_cell = no

# static or dynamic, static for 0 K, dynamic for finite-temperature
method_stress_statistics = static

# strains matrix for solve all elastic constants, asess or ohess or ulics
strains_matrix = ohess

# strains list for deforming lattice cell, 0 will be neglected because of 
# the initial optimization, if method_statistics = dynamic, the first one is used
strains_list = -0.06 -0.03 0.03 0.06  

# repeat numbers of three lattice vectors in conventional lattice for making
# supercell of molecular dynamics simulations (method_statistics = dynamic)
repeat_num = 1 1 1

# last number of steps for sampling stresses used in the dynamic method
num_last_samples = 500

#Potential directory - specify the location of your POTCAR files
potential_dir = /home/shahram/Sotf/fhi-aims.231212/fhi-aims.231212/species_defaults/defaults_2020/intermediate

# Plot parameters EVGB for 2D. Second argument turns on interactive plotly. Do not turn on for high-throughput calculations 
plotparameters = no,no

# Choose Elate parameters to plot. Alternatively, after obtaining your elastic tensor, run "elastool -elate to view on the web browser 
# None, print (just data), POISSON, SHEAR, LC, YOUNG, PUGH_RATIO, BULK,RATIO_COMPRESSIONAL_SHEAR,DEBYE_SPEED. You can use "all" for 2D only
elateparameters = None

# The parallel submiting commmd
parallel_submit_command = mpirun -np 12 aims.231212.scalapack.mpi.x > aims.out
```

**Are the first two entries correct?**

I am facing the following error:
```
Reading controlling parameters from elastool.in...

Optimizing the initial structure.

Traceback (most recent call last):
  File "/home/shahram/.local/bin/elastool_aims", line 122, in <module>
    pos_optimized = optimize_initial_str(pos_conv, cwd, parameters)
  File "/home/shahram/.local/lib/python3.10/site-packages/elastool_aims/optimize_initial_str.py", line 39, in optimize_initial_str
    pos_optimized = aims_run(" ".join(indict['parallel_submit_command']))
  File "/home/shahram/.local/lib/python3.10/site-packages/elastool_aims/aims_utils.py", line 189, in aims_run
    assert is_aims_success(), "aims run failed."
AssertionError: aims run failed.
```

Thank you for your guidance,
Shahram

**Comment by yaoyi92** [comment]
It seems the aims run failed. Do you see an `aims.out` file in the OPT folder?

**Comment by shahramyalameha** [comment]
aims.out:

`  MPI-parallelism will be employed.`

**Comment by yaoyi92** [comment]
What if you run `mpirun -np 12 aims.231212.scalapack.mpi.x > aims.out` directly in the OPT folder?

**Comment by shahramyalameha** [comment]
Thank you! I realized where I went wrong!
I had not entered the slow path correctly!

It works now!!....

**Comment by yaoyi92** [comment]
Great!
